name: Build and Package

on:
  workflow_dispatch:  # Adiciona o gatilho para disparar manualmente
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AdoptOpenJDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'
          java-package: 'jdk'
          architecture: 'x64'
          check-latest: true

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'

      - name: Save JAR artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-jar
          path: target/*.jar
