name: Build and Package

on:
  workflow_dispatch:  # Adiciona o gatilho para disparar manualmente
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Trivy Scan
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
    - name: Set up AdoptOpenJDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'  # Adoptium (anteriormente AdoptOpenJDK)
        java-version: '11'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: target/


